### ISSUE TITLE
Failed to run several projects

### ISSUE THREAD

**Issue by circler3** [Edgar077/PointClouds#2]
There are dependency errors when loading Microsoft.Kinect assembly when lanuching PointCloudScanner, both winform and wpf. The error code is 0x80131058. I found the configuration in the wpf project:
```xml
   <Reference Include="Microsoft.Kinect, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=AMD64">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\..\Program Files\Microsoft SDKs\Kinect\v2.0-DevPreview1311\Assemblies\Microsoft.Kinect.dll</HintPath>
    </Reference>
```
It seems that dependencies are referenced to local path. I find a *binextern* folder in the solution. But I can not solve the problem by copying the file to the *bin* folder and modify the path.

**Comment by kristof3** [comment]
A little late, but for future reference.
You need to download and install the Kinect SDK.
Direct link https://www.microsoft.com/en-us/download/details.aspx?id=44561
or search on the Microsoft website for the SDK

**Comment by circler3** [comment]
Thank you very much.
